config/routes.rb
RedmineApp::Application.routes.draw do
  resources :reminders, :except => :show
end

app/models/reminder.rb
class Reminder < ActiveRecord::Base
  include Redmine::SafeAttributes

  belongs_to :user

  validates_presence_of :text, :start_at, :end_at, :user_id
  validates_length_of :text, maximum: 254

  safe_attributes :text, :user_id, :start_at, :end_at, :visibility, :color, :finished

  scope :current, lambda{ where("finished = ? AND start_at <= ? AND end_at >= ?",
                                false, Date.today, Date.today) }
  scope :visible, lambda{
    if User.current.admin?
      all
    elsif User.current.respond_to?(:organization_id)
      organization_branch_items = []
      if User.current.organization
        (User.current.organization.ancestors | [User.current.organization]).each do |organization|
          organization_branch_items << "organization:#{organization.id}"
        end
      end
      where("visibility IS NULL OR visibility = 'all' OR visibility IN (?)", organization_branch_items)
    else
      where("visibility IS NULL OR visibility = 'all'")
    end
  }

  def color
    read_attribute(:color).presence || "salmon"
  end
end

app/controllers/reminders_controller.rb
class RemindersController < ApplicationController

  before_action :authorize_global
  before_action :find_reminder, :except => [:new, :create, :index]

  def index
    scope = Reminder

    @limit = per_page_option
    @reminder_count = scope.count
    @reminder_pages = Paginator.new @reminder_count, @limit, params[:page]
    @offset ||= @reminder_pages.offset
    @reminders =  scope.order("updated_at desc, end_at desc").limit(@limit).offset(@offset)

    render :layout => !request.xhr?
  end

  def new
    @reminder = Reminder.new
  end
  
  def create
    @reminder = Reminder.new
    @reminder.safe_attributes = params[:reminder]
    @reminder.user_id = User.current.id
    if @reminder.save
      flash[:notice] = l(:notice_successful_create)
      redirect_back_or_default reminders_path
    else
      render :action => "new"
    end
  end
  
  def edit
  end
  
  def update
    @reminder.safe_attributes = params[:reminder].merge(:user_id => User.current.id)
    if @reminder.save
      flash[:notice] = l(:notice_successful_update)
      redirect_back_or_default reminders_path
    else
      render :action => "edit"
    end
  end
  
  def destroy
    @reminder.destroy
    flash[:notice] = l(:notice_successful_delete)
    redirect_to reminders_path
  end

  private
  def find_reminder
    @reminder = Reminder.find(params[:id])
  end
end

app/helpers/reminders_helper.rb
module RemindersHelper
end

app/views/reminders/_boxes.html.erb
<% if User.current.allowed_to?(:view_reminders, nil, :global => true) && action_name!="flashs" %>
  <% cache ["reminders-on-my-page", "v2", Date.today, User.current, Reminder.maximum(:updated_at)] do %>
    <% reminders = Reminder.visible.current.order("end_at") %>
    <% if reminders.any? %>
      <div class=reminders>
        <h3><%= l(:label_reminder_plural) %></h3>
        <% reminders.each do |reminder| %>
          <%= content_tag :div, :class => "reminder reminder-#{reminder.color}" do %>
            <%= textilizable reminder.text %>
            <em class=info>
              <%= reminder.user %> |
              <%= link_to l(:button_edit).downcase, edit_reminder_path(reminder, :back_url => project_issues_path(Project.first)) %> |
              <%= link_to l(:field_finished).downcase, reminder_path(reminder, :back_url => project_issues_path(Project.first), :reminder => {:finished=>1}), :method => :put %>
            </em>
          <% end %>
        <% end %>
      </div>
      <div class=clear></div>
    <% end %>
  <% end %>
<% end %>

app/views/reminders/_form.html.erb
<%= error_messages_for 'reminder' %>

<!--[form:reminder]-->
<div class="splitcontentleft">
  <div class="reminder-form box tabular">
    <%= hidden_field_tag :back_url, params[:back_url] %>
    <p>
      <%= f.text_area :text, :size => "40x3", :label => l(:label_string) %>
    </p>
    <p>
      <%= f.text_field :start_at, :value => (@reminder.start_at || Date.today).strftime("%Y-%m-%d"), :size => 11 %>
      <%= calendar_for('reminder_start_at') %>
    </p>
    <p>
      <%= f.text_field :end_at, :value => (@reminder.end_at || Date.today).strftime("%Y-%m-%d"), :size => 11 %>
      <%= calendar_for('reminder_end_at') %>
    </p>
    <p>
      <%= f.check_box :finished %>
    </p>
  </div>
</div>
<div class="splitcontentright">
  <div class="reminder-form box tabular">
    <noscript>
      Your browser must be 10+ years old bro, sorry for you,
      but this form won't work without Javascript!
    </noscript>
    <p>
      <label><%= l(:label_color) %></label>
      <span class=colors>
        <% %w(salmon orange purple blue green clearblue grey).each do |color| %>
          <%= content_tag(:span, "A", :class => "color reminder-#{color}", :data => { :color => color }) %>
        <% end %>
        <%= f.hidden_field :color, :value => @reminder.color %>
      </span>
    </p>
  </div>
<% if Redmine::Plugin.installed?(:redmine_organizations) %>
  <div class="reminder-form box tabular">
    <p>
      <% orga_id = "#{@reminder.visibility}".scan(/^organization:(\d+)/) %>
      <label><%= l(:label_visibility) %></label>
      <span class=visibility>
        <label class=inline>
          <%= f.radio_button "visibility", "all",
                             :checked => ($1.blank?) %>
          <%= l(:label_all_authorized_users) %>
          (<%= Role.all.select{|r|r.has_permission?(:view_reminders)}.map(&:name).join(", ") %>)
        </label>
        <br>
      <% if User.current.organization.present? %>
        <% base_org = User.current.organization %>
        <% potential_organizations = base_org.ancestors + base_org.self_and_siblings.map{|o| o.self_and_descendants}.flatten %>
      <% end %>
      <% other_organization = Organization.find_by_id($1) if $1 %>
      <% if other_organization && $1.to_i != User.current.organization_id && !potential_organizations.include?(other_organization)  %>
        <label class=inline>
          <%= f.radio_button "visibility", "organization:#{$1}", :checked => true %>
          <%= other_organization.fullname %>
        </label>
        <br>
      <% end %>
      <% if potential_organizations.present? %>
        <% Organization.organization_tree(potential_organizations) do |organization, level| %>
          <label class=inline style="<%=  %>">
            <%= f.radio_button "visibility", "organization:#{organization.id}",
                              :checked => ($1.to_i == organization.id),
                              :style => "margin-left: #{(3 + (15 * level)).to_s + 'px;'}" %>
            <%= organization.name %>
          </label>
          <br>
        <% end %>
      <% end %>
      </span>
    </p>
  </div>
<% else %>
  <%= f.hidden_field :visibility, :value => "all" %>
<% end %>
</div>
<!--[eoform:reminder]-->

<div class=clear></div>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'reminders', :plugin => "redmine_reminders" %>
  <%= javascript_include_tag 'reminders', :plugin => "redmine_reminders" %>
<% end %>

app/views/reminders/edit.html.erb
<div class=contextual>
  <%= link_to l(:button_delete), reminder_path(@reminder),
              :data => {:confirm => l(:text_are_you_sure)},
              :method => :delete, :class => 'icon icon-del'
      #if User.current.allowed_to?(:delete_issues, @project)
  %>
</div>

<h2>
  <%= link_to l(:label_reminder_plural), reminders_path %>
  &#187; <%=l(:label_reminder_edit) %>
</h2>

<%= labelled_form_for @reminder, :url => reminder_path(@reminder), :html => { :class => nil } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<p><%= submit_tag l(:button_save) %></p>
<% end %>

app/views/reminders/index.html.erb
<div class=contextual>
  <%= link_to l(:label_reminder_add), new_reminder_path,
              :class => "icon icon-reminder", :id => "new-reminder" %>
</div>

<h2><%= l(:label_reminder_plural) %></h2>

<div class="autoscroll">
<table class="list">
  <thead><tr>
    <th>#</th>
    <th class=left><%= l(:label_string) %></th>
    <th class=left><%= l(:field_start_at) %></th>
    <th class=left><%= l(:field_end_at) %></th>
    <th class=left><%= l(:field_finished) %></th>
    <th class=left><%= l(:field_user) %> (<%= l(:field_updated_on).strip.downcase %>)</th>
    <th class=left></th>
  </tr></thead>
  <tbody>
<% @reminders.each do |reminder| %>
  <tr>
    <td class="id"><%= reminder.id %></td>
    <td class="text"><%= textilizable reminder.text %></td>
    <td class="start_at"><%= format_date(reminder.start_at) %></td>
    <td class="end_at"><%= format_date(reminder.end_at) %></td>
    <td class="finished center"><%= checked_image reminder.finished? %></td>
    <td class="user"><%= reminder.user %><em class=info>(<%= format_time(reminder.updated_at) %>)</em></td>
    <td class="buttons">
      <%= link_to l(:button_edit), edit_reminder_path(reminder), :class => "icon icon-edit" %>
      <%= link_to l(:button_delete), reminder_path(reminder),
                  :data => {:confirm => l(:text_are_you_sure)},
                  :method => :delete, :class => 'icon icon-del'
          #if User.current.allowed_to?(:delete_issues, @project)
      %>
    </td>
  </tr>
<% end %>
  </tbody>
</table>
</div>
<span class="pagination"><%= pagination_links_full @reminder_pages, @reminder_count %></span>

<% html_title(l(:label_reminder_plural)) -%>

<% content_for :header_tags do %>
  <%= stylesheet_link_tag 'reminders', :plugin => "redmine_reminders" %>
<% end %>

app/views/reminders/new.html.erb
<h2>
  <%= link_to l(:label_reminder_plural), reminders_path %>
  &#187; <%=l(:label_reminder_new) %>
</h2>

<%= labelled_form_for @reminder, :url => reminders_path, :html => { :class => nil } do |f| %>
	<%= render :partial => 'form', :locals => { :f => f } %>
	<p><%= submit_tag l(:button_create) %></p>
<% end %>